export const ReferenceBooks = [
  {
    link: "/reference-book//reference-book/nsi/transfer-destination-category-code",
    columns: {
      id: "number",
      codeId: "string",
      name: "string",
    },
  },
  {
    link: "/reference-book/nsi/organization-identification-code",
    columns: {
      id: "number",
      codeId: "string",
      name: "string",
    },
  },
  {
    link: "/reference-book/nsi/transfer-cancellation-code",
    columns: {
      id: "number",
      codeId: "string",
      name: "string",
    },
  },
  {
    link: "/reference-book/nsi/transfer-status-code",
    columns: {
      id: "number",
      codeId: "string",
      name: "string",
    },
  },
  {
    link: "/reference-book/nsi/balance-account-nb",
    columns: {
      id: "number",
      firstOrderBalanceAccountNumberId: "number",
      secondOrderBalanceAccountNumberId: "number",
      thirdOrderBalanceAccountNumberId: "number",
      fourthOrderBalanceAccountNumberId: "number",
      isClose: "boolean",
      characteristic: "number",
      accountNameDetails: "string",
    },
  },
  {
    link: "/reference-book/nsi/balance-account",
    columns: {
      id: "number",
      firstOrderBalanceAccountNumberId: "number",
      secondOrderBalanceAccountNumberId: "number",
      thirdOrderBalanceAccountNumberId: "number",
      fourthOrderBalanceAccountNumberId: "number",
      isClose: "boolean",
      characteristic: "number",
      accountNameDetails: "string",
    },
  },
  {
    link: "/reference-book/nsi/currency",
    columns: {
      id: "number",
      digitalCurrencyCodeId: "number",
      letterCurrencyCodeId: "string",
      name: "string",
      type: "number",
      decimalPlaces: "number",
      expirationDate: "string",
    },
  },
  {
    link: "/reference-book/nsi/exchange-rate",
    columns: {
      id: "number",
      digitalCurrencyCodeId: "number",
      letterCurrencyCodeId: "string",
      countUnits: "number",
      officialRate: "number",
      officialRatePerOneUnit: "number",
      dataId: "string",
    },
  },
  {
    link: "/reference-book/nsi/bank",
    columns: {
      id: "number",
      bankCodeId: "string",
      identificationCodeId: "string",
      name: "string",
      regionNumber: "string",
      paymentsType: "number",
      headBankUNUR: "string",
      reserve: "string",
    },
  },
  {
    link: "/reference-book/nsi/processing-code",
    columns: {
      id: "number",
      codeASId: "string",
      codeId: "string",
      name: "string",
    },
  },
  {
    link: "/reference-book/nsi/budget-payment-code",
    columns: {
      id: "number",
      paymentCodeId: "number",
      name: "string",
      isPayRepublicBudget: "string",
      isPayCustomsPayments: "string",
      isPaySocialProtectionFund: "string",
      isPayAdministrators: "string",
      isPayLocalBudget: "string",
      isPayAnotherClients: "string",
      isPayOutOfBudgetFonds: "string",
      isPayOutOfBudget: "string",
    },
  },
  {
    link: "/reference-book/nsi/country-codifier",
    columns: {
      id: "number",
      codeId: "number",
      codeA2: "string",
      codeA3: "string",
      digitalCurrencyCodeId: "number",
      letterCurrencyCode: "string",
      shortName: "string",
      fullName: "string",
    },
  },
  {
    link: "/reference-book/nsi/republican-budget-account",
    columns: {
      id: "number",
      identificationCodeId: "string",
      republicanBudgetAccountId: "string",
      digitalCurrencyCodeId: "number",
      actualBeneficiaryUNPId: "number",
      actualBeneficiaryName: "string",
      beneficiaryName: "string",
      beneficiaryUNPId: "number",
    },
  },
  {
    link: "/reference-book/nsi/bank-id-code",
    columns: {
      id: "number",
      unuId: "string",
      bicId: "string",
      status: "number",
      accountNumber: "string",
      unp: "number",
      bankName: "string",
      city: "string",
      controlCode: "string",
      controlDate: "string",
      bicPlus: "string",
    },
  },
  {
    link: "/reference-book/nsi/biss-member",
    columns: {
      id: "number",
      unurId: "number",
      bankIdentificationCodeId: "string",
      membersAuthenticationCodeForBISSId: "string",
      status: "number",
      type: "number",
      shortName: "string",
      cityAndFullName: "string",
      phone: "string",
      index: "string",
    },
  },
  {
    link: "/reference-book/nsi/payment-priority-code",
    columns: {
      id: "number",
      primaryCodeId: "number",
      name: "string",
    },
  },
  {
    link: "/reference-book/nsi/local-budget-account",
    columns: {
      id: "number",
      identificationCodeId: "string",
      localBudgetAccountId: "string",
      digitalCurrencyCodeId: "number",
      beneficiaryUNPId: "number",
      actualBeneficiaryName: "string",
      beneficiaryName: "string",
      actualBeneficiaryUNPId: "number",
    },
  },
  {
    link: "/reference-book/nsi/subject-statuses",
    columns: {
      id: "number",
      codeId: "string",
      name: "string",
      isUsingBisORIis: "number",
      isUsingFulfillingMonetaryObligationsSystem: "number",
    },
  },
];
